"""Signal 1 — LLM holistic judgment via Groq.

Asks ``llama-3.3-70b-versatile`` to read the text the way a person would and estimate the
probability that it was AI-generated. This captures *semantic and stylistic coherence* — a
holistic judgment no statistic can make.

Returns ``P(AI)`` in ``[0, 1]``. Raises a clear error if the API key is missing so failures
are obvious rather than silent.
"""

from __future__ import annotations

import json

from groq import Groq

from config import GROQ_API_KEY, LLM_MODEL

MODEL = LLM_MODEL

_SYSTEM_PROMPT = (
    "You are a forensic text analyst for a creative-writing platform. Your job is to estimate "
    "the probability that a piece of text was generated by an AI language model rather than "
    "written by a human. Consider semantic coherence, stylistic fingerprints, generic vs. "
    "specific detail, emotional texture, and the natural irregularity of human writing. "
    "AI text tends to be fluent, evenly structured, generic, and hedge-y; human text tends to "
    "be more irregular, specific, and idiosyncratic. "
    "Respond with ONLY a compact JSON object of the form "
    '{"ai_probability": <float between 0 and 1>, "reasoning": "<one short sentence>"}. '
    "Do not include any text outside the JSON."
)

_client: Groq | None = None


def _get_client() -> Groq:
    global _client
    if _client is None:
        if not GROQ_API_KEY:
            raise RuntimeError(
                "GROQ_API_KEY is not set. Copy .env.example to .env and add your key "
                "(GROQ_API_KEY=your_key_here) before using the LLM signal."
            )
        _client = Groq(api_key=GROQ_API_KEY)
    return _client


def _clamp(value: float) -> float:
    return max(0.0, min(1.0, value))


def llm_signal(text: str) -> dict:
    """Return ``{"score": P(AI), "reasoning": str}`` for ``text``.

    ``score`` is the probability the text is AI-generated, in ``[0, 1]``.
    """
    client = _get_client()
    completion = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": f"Analyze this text:\n\n{text}"},
        ],
        temperature=0.0,
        max_tokens=200,
        response_format={"type": "json_object"},
    )
    raw = completion.choices[0].message.content or "{}"
    try:
        parsed = json.loads(raw)
        score = _clamp(float(parsed.get("ai_probability", 0.5)))
        reasoning = str(parsed.get("reasoning", "")).strip()
    except (json.JSONDecodeError, TypeError, ValueError):
        # If the model returns something unparseable, fall back to maximum uncertainty
        # rather than guessing — the other two signals still vote.
        score, reasoning = 0.5, "Unparseable LLM response; defaulted to 0.5."
    return {"score": score, "reasoning": reasoning}
